# Generated by Django 4.1.2 on 2023-01-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoUpload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='refVideoUpload')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoUpload',
        ),
    ]
