# Generated by Django 4.1.2 on 2023-01-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoUpload', '0002_videouploadmodel_delete_videoupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='refImageUpload')),
            ],
        ),
        migrations.RenameModel(
            old_name='VideoUploadModel',
            new_name='VideoModel',
        ),
    ]
