name: Docker Image CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run the Containers
      run: docker-compose up -d --build
    - name: Stop Containers
      if: always()
      run: docker-compose down
